[package]
name = "atlas-arch-rpc-datasource"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/saturnBTC/atlas"
license = "MIT"
description = "Atlas datasource that streams updates via Arch RPC."

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
hex = { workspace = true }

arch_sdk = { workspace = true }
arch_program = { workspace = true }

atlas-arch = { workspace = true }

titan-client = { workspace = true }